server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/clmoten84/gearstack-config
          username: 'clmoten84'
          password: '!8LamonT4!'